services:
  backend:
    image: wordle_clone:latest
    build: ./backend
    ports:
      - 3000:3000
  frontend:
    image: wordle_frontend:latest
    build: ./frontend
  server:
    image: server:latest
    build: ./server
    ports:
      - 8080:8080
    depends_on:
      - frontend
