services:
  database:
    image: mongo:5.0.7
    environment:
      MONGO_INITDB_DATABASE: wordle_clone_production
    ports:
      - 27017:27017
    networks:
      back_tier:
        aliases:
          - wordle_db
  backend:
    image: wordle_clone:latest
    build:
      context: ./backend
      args:
        MONGODB_URI: mongodb://wordle_db:27017/wordle_clone_production
    ports:
      - 3000:3000
    depends_on:
      - database
    networks:
      - back_tier
  frontend:
    image: wordle_frontend:latest
    build: ./frontend
  server:
    image: server:latest
    build: ./server
    ports:
      - 8080:8080
    depends_on:
      - frontend

networks:
  back_tier:
