services:
  database:
    image: mongo:5.0.7
    container_name: wordle_database
    environment:
      MONGO_INITDB_DATABASE: wordle_clone_production
    volumes:
      - wordle_data:/data/db
      - wordle_data_config:/data/configdb
    networks:
      back_tier:
  backend:
    image: wordle_backend:latest
    container_name: wordle_backend
    build:
      context: ./backend
      args:
        MONGODB_URI: mongodb://wordle_database:27017/wordle_clone_production
    ports:
      - 3000:3000
    depends_on:
      - database
    networks:
      - back_tier
  frontend:
    image: wordle_frontend:latest
    container_name: wordle_frontend
    build: ./frontend
    ports:
      - 8080:8080

volumes:
  wordle_data:
    name: wordle_data
  wordle_data_config:
    name: wordle_data_config

networks:
  back_tier:
